# Generated by Django 5.0.7 on 2024-07-21 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findme', '0002_a_book_recommend_a_song_recommend_b_book_recommend_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a_song_recommend',
            name='description',
        ),
        migrations.RemoveField(
            model_name='b_song_recommend',
            name='description',
        ),
        migrations.RemoveField(
            model_name='c_song_recommend',
            name='description',
        ),
    ]
