# Generated by Django 5.0.7 on 2024-07-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findme', '0003_remove_a_song_recommend_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_song_recommend',
            name='image',
            field=models.ImageField(upload_to='songs/A'),
        ),
        migrations.AlterField(
            model_name='b_song_recommend',
            name='image',
            field=models.ImageField(upload_to='songs/B'),
        ),
        migrations.AlterField(
            model_name='c_song_recommend',
            name='image',
            field=models.ImageField(upload_to='songs/C'),
        ),
    ]
