# Generated by Django 5.0.7 on 2024-08-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perm', '0004_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
